// Generated by typography-system/scripts/build-reade-font-pack.py. Do not edit.
export const READER_FONT_PACK = {
  "schemaVersion": 1,
  "packId": "reade-reader-fonts",
  "inventorySignature": "a0b8235c7bd945720bc17c3cd09ebc55d6504e7b65759ee5f642d59313fedf30",
  "fonts": [
    {
      "id": "charter",
      "label": "Charter",
      "script": "latin",
      "cssFamily": "Reade charter",
      "description": "稳健紧凑的经典屏幕阅读衬线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": true,
      "hasRealStrong": true,
      "availableWeights": [
        400,
        700
      ],
      "variableAxes": []
    },
    {
      "id": "crimson-pro",
      "label": "Crimson Pro",
      "script": "latin",
      "cssFamily": "Reade crimson-pro",
      "description": "现代屏幕友好的书籍衬线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": true,
      "hasRealStrong": true,
      "availableWeights": [
        400
      ],
      "variableAxes": [
        {
          "tag": "wght",
          "name": "Weight",
          "min": 200.0,
          "default": 400.0,
          "max": 900.0
        }
      ]
    },
    {
      "id": "eb-garamond",
      "label": "EB Garamond",
      "script": "latin",
      "cssFamily": "Reade eb-garamond",
      "description": "古典文学与旧式书籍气质",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": true,
      "hasRealStrong": true,
      "availableWeights": [
        400
      ],
      "variableAxes": [
        {
          "tag": "wght",
          "name": "Weight",
          "min": 400.0,
          "default": 400.0,
          "max": 800.0
        }
      ]
    },
    {
      "id": "libre-baskerville",
      "label": "Libre Baskerville",
      "script": "latin",
      "cssFamily": "Reade libre-baskerville",
      "description": "结实传统的屏幕书籍衬线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": true,
      "hasRealStrong": true,
      "availableWeights": [
        400
      ],
      "variableAxes": [
        {
          "tag": "wght",
          "name": "Weight",
          "min": 400.0,
          "default": 400.0,
          "max": 700.0
        }
      ]
    },
    {
      "id": "lora",
      "label": "Lora",
      "script": "latin",
      "cssFamily": "Reade lora",
      "description": "温暖、带书写感的杂志衬线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": true,
      "hasRealStrong": true,
      "availableWeights": [
        400
      ],
      "variableAxes": [
        {
          "tag": "wght",
          "name": "Weight",
          "min": 400.0,
          "default": 400.0,
          "max": 700.0
        }
      ]
    },
    {
      "id": "roboto-slab",
      "label": "Roboto Slab",
      "script": "latin",
      "cssFamily": "Reade roboto-slab",
      "description": "强调结构的现代粗衬线",
      "bodyRecommended": false,
      "licenseStatus": "verified-local-or-embedded",
      "warning": "正文密度偏高，优先用于标题或技术编辑风格",
      "hasItalic": false,
      "hasRealStrong": true,
      "availableWeights": [
        400
      ],
      "variableAxes": [
        {
          "tag": "wght",
          "name": "Weight",
          "min": 100.0,
          "default": 400.0,
          "max": 900.0
        }
      ]
    },
    {
      "id": "alegreya",
      "label": "Alegreya",
      "script": "latin",
      "cssFamily": "Reade alegreya",
      "description": "节奏活跃的人文书写衬线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": true,
      "hasRealStrong": true,
      "availableWeights": [
        400
      ],
      "variableAxes": [
        {
          "tag": "wght",
          "name": "Weight",
          "min": 400.0,
          "default": 400.0,
          "max": 900.0
        }
      ]
    },
    {
      "id": "atkinson-hyperlegible",
      "label": "Atkinson Hyperlegible",
      "script": "latin",
      "cssFamily": "Reade atkinson-hyperlegible",
      "description": "强调字符辨识度的无衬线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": true,
      "hasRealStrong": true,
      "availableWeights": [
        400,
        700
      ],
      "variableAxes": []
    },
    {
      "id": "ibm-plex-serif",
      "label": "IBM Plex Serif",
      "script": "latin",
      "cssFamily": "Reade ibm-plex-serif",
      "description": "理性、技术感的现代衬线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": true,
      "hasRealStrong": true,
      "availableWeights": [
        100,
        200,
        300,
        400,
        500,
        600,
        700
      ],
      "variableAxes": []
    },
    {
      "id": "literata",
      "label": "Literata",
      "script": "latin",
      "cssFamily": "Reade literata",
      "description": "面向电子书长读的文学衬线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": true,
      "hasRealStrong": true,
      "availableWeights": [
        400
      ],
      "variableAxes": [
        {
          "tag": "opsz",
          "name": "Optical size",
          "min": 7.0,
          "default": 12.0,
          "max": 72.0
        },
        {
          "tag": "wght",
          "name": "Weight",
          "min": 200.0,
          "default": 400.0,
          "max": 900.0
        }
      ]
    },
    {
      "id": "merriweather",
      "label": "Merriweather",
      "script": "latin",
      "cssFamily": "Reade merriweather",
      "description": "较深、结实的屏幕阅读衬线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": true,
      "hasRealStrong": true,
      "availableWeights": [
        300
      ],
      "variableAxes": [
        {
          "tag": "opsz",
          "name": "Optical size",
          "min": 18.0,
          "default": 18.0,
          "max": 144.0
        },
        {
          "tag": "wdth",
          "name": "Width",
          "min": 87.0,
          "default": 100.0,
          "max": 112.0
        },
        {
          "tag": "wght",
          "name": "Weight",
          "min": 300.0,
          "default": 300.0,
          "max": 900.0
        }
      ]
    },
    {
      "id": "newsreader",
      "label": "Newsreader",
      "script": "latin",
      "cssFamily": "Reade newsreader",
      "description": "报刊编辑与长文阅读衬线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": true,
      "hasRealStrong": true,
      "availableWeights": [
        400
      ],
      "variableAxes": [
        {
          "tag": "opsz",
          "name": "Optical Size",
          "min": 6.0,
          "default": 18.0,
          "max": 72.0
        },
        {
          "tag": "wght",
          "name": "Weight",
          "min": 200.0,
          "default": 400.0,
          "max": 800.0
        }
      ]
    },
    {
      "id": "noto-serif",
      "label": "Noto Serif",
      "script": "latin",
      "cssFamily": "Reade noto-serif",
      "description": "中性、兼容性稳健的衬线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": true,
      "hasRealStrong": true,
      "availableWeights": [
        400
      ],
      "variableAxes": [
        {
          "tag": "wdth",
          "name": "Width",
          "min": 62.5,
          "default": 100.0,
          "max": 100.0
        },
        {
          "tag": "wght",
          "name": "Weight",
          "min": 100.0,
          "default": 400.0,
          "max": 900.0
        }
      ]
    },
    {
      "id": "pt-serif",
      "label": "PT Serif",
      "script": "latin",
      "cssFamily": "Reade pt-serif",
      "description": "传统而不过时的编辑衬线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": true,
      "hasRealStrong": true,
      "availableWeights": [
        400,
        700
      ],
      "variableAxes": []
    },
    {
      "id": "source-serif-4",
      "label": "Source Serif 4",
      "script": "latin",
      "cssFamily": "Reade source-serif-4",
      "description": "现代、均衡且层级完整的正文衬线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": true,
      "hasRealStrong": true,
      "availableWeights": [
        400
      ],
      "variableAxes": [
        {
          "tag": "opsz",
          "name": "Optical Size",
          "min": 8.0,
          "default": 20.0,
          "max": 60.0
        },
        {
          "tag": "wght",
          "name": "Weight",
          "min": 200.0,
          "default": 400.0,
          "max": 900.0
        }
      ]
    },
    {
      "id": "spectral",
      "label": "Spectral",
      "script": "latin",
      "cssFamily": "Reade spectral",
      "description": "具有编辑表现力的现代衬线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": true,
      "hasRealStrong": true,
      "availableWeights": [
        200,
        300,
        400,
        500,
        600,
        700,
        800
      ],
      "variableAxes": []
    },
    {
      "id": "kinghwa-old-song",
      "label": "京华老宋体",
      "script": "cjk",
      "cssFamily": "Reade kinghwa-old-song",
      "description": "复古铅印质感的老宋体",
      "bodyRecommended": false,
      "licenseStatus": "claimed-by-local-index-unverified",
      "warning": "重新分发证据未独立核实；层级有限，适合明确的复古阅读方向",
      "hasItalic": false,
      "hasRealStrong": false,
      "availableWeights": [
        400
      ],
      "variableAxes": []
    },
    {
      "id": "source-han-serif-sc",
      "label": "思源宋体 SC",
      "script": "cjk",
      "cssFamily": "Reade source-han-serif-sc",
      "description": "简中宋体的中性专业基线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": false,
      "hasRealStrong": true,
      "availableWeights": [
        250,
        300,
        400,
        500,
        600,
        700,
        900
      ],
      "variableAxes": []
    },
    {
      "id": "genyo-min",
      "label": "源样明体",
      "script": "cjk",
      "cssFamily": "Reade genyo-min",
      "description": "台湾字形取向的传统明体",
      "bodyRecommended": false,
      "licenseStatus": "verified-local-or-embedded",
      "warning": "区域字形偏台湾，不作为 zh-CN 默认候选",
      "hasItalic": false,
      "hasRealStrong": true,
      "availableWeights": [
        250,
        300,
        400,
        500,
        600,
        700,
        900
      ],
      "variableAxes": []
    },
    {
      "id": "genryu-min",
      "label": "源流明体",
      "script": "cjk",
      "cssFamily": "Reade genryu-min",
      "description": "流丽雕刻感的台湾字形明体",
      "bodyRecommended": false,
      "licenseStatus": "verified-local-or-embedded",
      "warning": "区域字形偏台湾，不作为 zh-CN 默认候选",
      "hasItalic": false,
      "hasRealStrong": true,
      "availableWeights": [
        250,
        300,
        400,
        500,
        600,
        700,
        900
      ],
      "variableAxes": []
    },
    {
      "id": "misans",
      "label": "MiSans",
      "script": "cjk",
      "cssFamily": "Reade misans",
      "description": "现代、中性的屏幕黑体",
      "bodyRecommended": true,
      "licenseStatus": "claimed-by-local-index-unverified",
      "warning": "重新分发证据未独立核实",
      "hasItalic": false,
      "hasRealStrong": true,
      "availableWeights": [
        100,
        200,
        300,
        400,
        500,
        600,
        700,
        900
      ],
      "variableAxes": []
    },
    {
      "id": "source-han-sans-cn",
      "label": "思源黑体 CN",
      "script": "cjk",
      "cssFamily": "Reade source-han-sans-cn",
      "description": "简中黑体的中性专业基线",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": false,
      "hasRealStrong": true,
      "availableWeights": [
        250,
        300,
        350,
        400,
        500,
        700,
        900
      ],
      "variableAxes": []
    },
    {
      "id": "sarasa-gothic-sc",
      "label": "更纱黑体 SC",
      "script": "cjk",
      "cssFamily": "Reade sarasa-gothic-sc",
      "description": "适合技术混排的黑体",
      "bodyRecommended": true,
      "licenseStatus": "claimed-by-local-index-unverified",
      "warning": "第三方 SC 转包；重新分发证据未独立核实",
      "hasItalic": false,
      "hasRealStrong": true,
      "availableWeights": [
        300,
        400,
        700
      ],
      "variableAxes": []
    },
    {
      "id": "huiwen-mincho",
      "label": "汇文明朝体",
      "script": "cjk",
      "cssFamily": "Reade huiwen-mincho",
      "description": "旧式中文印刷所气质的明朝体",
      "bodyRecommended": false,
      "licenseStatus": "claimed-by-local-index-unverified",
      "warning": "重新分发证据未独立核实；单一字重",
      "hasItalic": false,
      "hasRealStrong": false,
      "availableWeights": [
        400
      ],
      "variableAxes": []
    },
    {
      "id": "lxgw-wenkai",
      "label": "霞鹜文楷",
      "script": "cjk",
      "cssFamily": "Reade lxgw-wenkai",
      "description": "温润、带手写感的阅读楷体",
      "bodyRecommended": true,
      "licenseStatus": "verified-local-or-embedded",
      "warning": null,
      "hasItalic": false,
      "hasRealStrong": true,
      "availableWeights": [
        400,
        500
      ],
      "variableAxes": []
    },
    {
      "id": "smiley-sans",
      "label": "得意黑",
      "script": "cjk",
      "cssFamily": "Reade smiley-sans",
      "description": "窄长斜切的展示字体",
      "bodyRecommended": false,
      "licenseStatus": "verified-local-or-embedded",
      "warning": "源 face 为固定斜切造型并映射为 CSS normal；仅建议用于标题，高级选择正文时需明确承担可读性风险",
      "hasItalic": false,
      "hasRealStrong": false,
      "availableWeights": [
        400
      ],
      "variableAxes": []
    }
  ],
  "pairings": [
    {
      "id": "balanced-modern-book",
      "label": "现代书卷",
      "cjkFontId": "source-han-serif-sc",
      "latinFontId": "source-serif-4",
      "tone": "平衡",
      "description": "现代、稳健的长文默认候选"
    },
    {
      "id": "neutral-system-serif",
      "label": "中性宋体",
      "cjkFontId": "source-han-serif-sc",
      "latinFontId": "noto-serif",
      "tone": "保守",
      "description": "低风险、兼容性优先的衬线组合"
    },
    {
      "id": "editorial-reading",
      "label": "编辑阅读",
      "cjkFontId": "source-han-serif-sc",
      "latinFontId": "newsreader",
      "tone": "表达性",
      "description": "带优质报刊与编辑气质"
    },
    {
      "id": "sturdy-classic-screen",
      "label": "经典屏读",
      "cjkFontId": "source-han-serif-sc",
      "latinFontId": "charter",
      "tone": "平衡",
      "description": "结实、克制的经典屏幕阅读"
    },
    {
      "id": "ebook-literary",
      "label": "电子书文学",
      "cjkFontId": "source-han-serif-sc",
      "latinFontId": "literata",
      "tone": "平衡",
      "description": "偏电子书与文学长读"
    },
    {
      "id": "warm-essay",
      "label": "温润散文",
      "cjkFontId": "lxgw-wenkai",
      "latinFontId": "lora",
      "tone": "表达性",
      "description": "柔和、有人文手写感"
    },
    {
      "id": "humanist-literary",
      "label": "人文书写",
      "cjkFontId": "lxgw-wenkai",
      "latinFontId": "alegreya",
      "tone": "表达性",
      "description": "节奏活跃的书写型组合"
    },
    {
      "id": "historic-print",
      "label": "古典铅印",
      "cjkFontId": "kinghwa-old-song",
      "latinFontId": "eb-garamond",
      "tone": "表达性",
      "description": "强烈的历史书籍与铅印气质"
    },
    {
      "id": "old-publication",
      "label": "旧刊明朝",
      "cjkFontId": "huiwen-mincho",
      "latinFontId": "libre-baskerville",
      "tone": "表达性",
      "description": "旧中文刊物与传统西文书籍的组合"
    },
    {
      "id": "accessible-modern-sans",
      "label": "清晰现代",
      "cjkFontId": "misans",
      "latinFontId": "atkinson-hyperlegible",
      "tone": "保守",
      "description": "字符辨识与现代屏显优先"
    },
    {
      "id": "technical-neutral-sans",
      "label": "技术中性",
      "cjkFontId": "source-han-sans-cn",
      "latinFontId": "atkinson-hyperlegible",
      "tone": "保守",
      "description": "适合技术长文的清晰无衬线组合"
    },
    {
      "id": "technical-editorial",
      "label": "技术编辑",
      "cjkFontId": "sarasa-gothic-sc",
      "latinFontId": "roboto-slab",
      "tone": "表达性",
      "description": "技术黑体与粗衬线的有意对比"
    }
  ]
} as const;

export type GeneratedReaderFont = (typeof READER_FONT_PACK.fonts)[number];
export type GeneratedReaderFontId = GeneratedReaderFont['id'];
export type GeneratedReaderFontPair = (typeof READER_FONT_PACK.pairings)[number];
export type GeneratedReaderFontPairId = GeneratedReaderFontPair['id'];
