//! File IO for the annotation export/import round (§5.7).
//!
//! Both commands drive the native file dialog *from Rust*: the frontend
//! never passes a filesystem path over IPC, so no arbitrary-path read or
//! write surface exists — the only reachable paths are the ones the user
//! just picked in the dialog of that very call. This also keeps
//! `capabilities/default.json` untouched: capability permissions gate the
//! JS-side plugin IPC, not the Rust-side dialog API used here.

use std::{fs, path::Path};

use serde::Serialize;
use tauri_plugin_dialog::DialogExt;

use crate::library::CommandResult;

/// Export payloads above this size are refused. The 10,000-annotation
/// import cap serializes to a few dozen MiB at worst, far below this.
const MAX_EXPORT_CONTENT_BYTES: usize = 64 * 1024 * 1024;
/// Import files above this size are refused before their content is read.
const MAX_IMPORT_FILE_BYTES: u64 = 32 * 1024 * 1024;
const MAX_EXPORT_FILE_NAME_CHARS: usize = 128;

/// Allowed export types; the extension picks the dialog filter.
const EXPORT_FILE_KINDS: &[(&str, &str)] = &[("json", "JSON 文件"), ("csv", "CSV 文件")];

/// The suggested file name is generated by the frontend, but it is still
/// validated down to a conservative charset (no separators, no traversal,
/// no leading dot) with a known extension before reaching the dialog.
fn validate_export_file_name(name: &str) -> CommandResult<(&'static str, &'static str)> {
    if name.is_empty() || name.len() > MAX_EXPORT_FILE_NAME_CHARS || name.starts_with('.') {
        return Err("Export file name is invalid".to_owned());
    }
    if !name
        .bytes()
        .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
    {
        return Err("Export file name contains unsupported characters".to_owned());
    }
    for (extension, label) in EXPORT_FILE_KINDS.iter().copied() {
        if let Some(stem) = name.strip_suffix(extension) {
            if stem.ends_with('.') && stem.len() > 1 {
                return Ok((extension, label));
            }
        }
    }
    Err("Export file type is not supported".to_owned())
}

fn validate_export_contents(contents: &str) -> CommandResult<()> {
    if contents.len() > MAX_EXPORT_CONTENT_BYTES {
        return Err("Export content is too large".to_owned());
    }
    Ok(())
}

/// Size- and type-capped read of a user-picked import file.
fn read_import_file(path: &Path) -> CommandResult<String> {
    let metadata =
        fs::metadata(path).map_err(|error| format!("Cannot inspect the import file: {error}"))?;
    if !metadata.is_file() {
        return Err("The selected import path is not a regular file".to_owned());
    }
    if metadata.len() > MAX_IMPORT_FILE_BYTES {
        return Err(format!(
            "Import file exceeds the {} MiB limit",
            MAX_IMPORT_FILE_BYTES / (1024 * 1024)
        ));
    }
    let bytes = fs::read(path).map_err(|error| format!("Cannot read the import file: {error}"))?;
    String::from_utf8(bytes).map_err(|_| "Import file is not valid UTF-8 text".to_owned())
}

/// Opens a save dialog for the annotation export and writes `contents` to
/// the chosen path. Returns the written path, or `None` when the user
/// cancelled. Declared `async` so the blocking dialog call runs on the
/// async runtime instead of the main thread.
#[tauri::command]
pub async fn export_annotations_file(
    app: tauri::AppHandle,
    default_name: String,
    contents: String,
) -> CommandResult<Option<String>> {
    let (extension, label) = validate_export_file_name(&default_name)?;
    validate_export_contents(&contents)?;
    let Some(picked) = app
        .dialog()
        .file()
        .add_filter(label, &[extension])
        .set_file_name(default_name.as_str())
        .blocking_save_file()
    else {
        return Ok(None);
    };
    let path = picked
        .into_path()
        .map_err(|error| format!("Cannot use the selected export path: {error}"))?;
    fs::write(&path, contents.as_bytes())
        .map_err(|error| format!("Cannot write the export file: {error}"))?;
    Ok(Some(path.display().to_string()))
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ImportFilePayload {
    pub file_name: String,
    pub contents: String,
}

/// Opens an open dialog and returns the picked file's text content (size-
/// and UTF-8-checked). Returns `None` when the user cancelled. Parsing and
/// validation of the content happen in the shared frontend core.
#[tauri::command]
pub async fn pick_annotations_import_file(
    app: tauri::AppHandle,
) -> CommandResult<Option<ImportFilePayload>> {
    let Some(picked) = app
        .dialog()
        .file()
        .add_filter("JSON 文件", &["json"])
        .blocking_pick_file()
    else {
        return Ok(None);
    };
    let path = picked
        .into_path()
        .map_err(|error| format!("Cannot use the selected import path: {error}"))?;
    let contents = read_import_file(&path)?;
    let file_name = path
        .file_name()
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_else(|| "import.json".to_owned());
    Ok(Some(ImportFilePayload {
        file_name,
        contents,
    }))
}

#[cfg(test)]
mod tests {
    use std::fs::File;

    use tempfile::tempdir;

    use super::*;

    #[test]
    fn export_file_names_are_validated() {
        assert_eq!(
            validate_export_file_name("reade-annotations-20260813.json").expect("json"),
            ("json", "JSON 文件")
        );
        assert_eq!(
            validate_export_file_name("reade-annotations.csv").expect("csv"),
            ("csv", "CSV 文件")
        );
        for name in [
            "",
            ".hidden.json",
            "no-extension",
            "notes.txt",
            "dir/escape.json",
            "dir\\escape.json",
            "..\\up.json",
            "空格 name.json",
            "trailingdotjson",
            ".json",
        ] {
            assert!(
                validate_export_file_name(name).is_err(),
                "{name} should be rejected"
            );
        }
        let long_name = format!("{}.json", "a".repeat(200));
        assert!(validate_export_file_name(&long_name).is_err());
    }

    #[test]
    fn export_contents_are_size_capped() {
        assert!(validate_export_contents("{}").is_ok());
        let oversized = "x".repeat(MAX_EXPORT_CONTENT_BYTES + 1);
        assert!(validate_export_contents(&oversized).is_err());
    }

    #[test]
    fn import_read_round_trips_utf8_text() {
        let directory = tempdir().expect("temp dir");
        let path = directory.path().join("import.json");
        fs::write(&path, "{\"formatVersion\":1,\"中文\":true}").expect("write");
        assert_eq!(
            read_import_file(&path).expect("read"),
            "{\"formatVersion\":1,\"中文\":true}"
        );
    }

    #[test]
    fn import_read_rejects_oversized_files_without_reading_them() {
        let directory = tempdir().expect("temp dir");
        let path = directory.path().join("huge.json");
        let file = File::create(&path).expect("create");
        // A sparse set_len makes the metadata report an oversized file
        // without actually writing gigabytes.
        file.set_len(MAX_IMPORT_FILE_BYTES + 1).expect("set len");
        drop(file);
        let error = read_import_file(&path).expect_err("must reject");
        assert!(error.contains("limit"), "unexpected error: {error}");
    }

    #[test]
    fn import_read_rejects_directories_and_non_utf8() {
        let directory = tempdir().expect("temp dir");
        assert!(read_import_file(directory.path()).is_err());
        let path = directory.path().join("binary.json");
        fs::write(&path, [0xffu8, 0xfe, 0xff, 0x00]).expect("write");
        let error = read_import_file(&path).expect_err("must reject");
        assert!(error.contains("UTF-8"), "unexpected error: {error}");
    }
}
